name: ci

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:

jobs:
  test:
    name: test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip1

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --locked

      - name: Test
        run: cargo test --locked --no-fail-fast
